import { auth, db } from './firebase.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import { collection, addDoc, doc, getDoc, getDocs, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js';

const login=document.getElementById('adminLogin'),shell=document.getElementById('adminShell'),error=document.getElementById('loginError');
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function isAdmin(user){if(!user)return false;const p=await getDoc(doc(db,'users',user.uid));return p.exists()&&p.data().role==='admin'}
async function showAdmin(user){if(await isAdmin(user)){login.style.display='none';shell.classList.add('show');await refreshDashboard()}else{shell.classList.remove('show');login.style.display='grid';if(user){error.textContent='هذا الحساب لا يملك صلاحية الإدارة';await signOut(auth)}}}
document.getElementById('adminLoginBtn').addEventListener('click',async()=>{error.textContent='';try{const c=await signInWithEmailAndPassword(auth,adminEmail.value.trim(),adminPass.value);await showAdmin(c.user)}catch(e){error.textContent='البريد أو كلمة المرور غير صحيحة'}});
document.getElementById('adminLogoutBtn').addEventListener('click',async()=>{await signOut(auth);location.reload()});
async function refreshDashboard(){const [children,workshops,bookings,feedback]=await Promise.all([getDocs(collection(db,'children')),getDocs(collection(db,'workshops')),getDocs(collection(db,'bookings')),getDocs(collection(db,'feedback'))]);childrenStat.textContent=children.size;workshopsStat.textContent=workshops.size;bookingsStat.textContent=bookings.size;feedbackStat.textContent=feedback.size;workshopRows.innerHTML='';workshops.forEach(d=>{const w=d.data();workshopRows.insertAdjacentHTML('beforeend',`<tr><td>${esc(w.name)}</td><td>${esc(w.date)}</td><td>${esc(w.time)}</td><td>${esc(w.park)}</td><td>${esc(w.seats)}</td></tr>`)});if(workshops.empty)workshopRows.innerHTML='<tr><td colspan="5">لا توجد ورش مضافة حتى الآن</td></tr>'}
window.addWorkshop=async()=>{const u=auth.currentUser;if(!u||!(await isAdmin(u))){alert('غير مصرح');return}const n=wName.value.trim();if(!n||!wDate.value||!wTime.value){alert('أكمل اسم الورشة والتاريخ والوقت');return}await addDoc(collection(db,'workshops'),{name:n,date:wDate.value,time:wTime.value,seats:Number(wSeats.value||0),park:wPark.value.trim(),age:wAge.value.trim(),description:wDesc.value.trim(),createdBy:u.uid,createdAt:serverTimestamp()});wName.value=wDate.value=wTime.value=wSeats.value=wPark.value=wAge.value=wDesc.value='';await refreshDashboard();alert('تم حفظ الورشة في Firebase')};
onAuthStateChanged(auth,u=>showAdmin(u).catch(()=>{}));
