import { auth, db } from './firebase.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, updateProfile } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import { collection, addDoc, doc, setDoc, getDoc, getDocs, query, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js';

const $=id=>document.getElementById(id), esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
window.openModal=id=>$(id)?.classList.add('show'); window.closeModal=id=>$(id)?.classList.remove('show');
window.toast=t=>{const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)};
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')}));
const activities=[['القصص والقراءة','نقرأ ونحكي ونصنع خيالًا أجمل.','story'],['الرسم والفنون','مساحة للألوان والإبداع والتعبير.','art'],['الزراعة والبيئة','نتعلم كيف نعتني بالنبات والطبيعة.','garden'],['الألعاب الجماعية','مرح وحركة وتعاون بين الأطفال.','games']];
function renderActivities(){const box=$('activityCards');if(!box)return;box.innerHTML=activities.map((a,i)=>`<article class="card"><div class="pic ${a[2]}"></div><div class="pad"><h3>${a[0]}</h3><p>${a[1]}</p><button class="btn" onclick="location.hash='booking'">عرض المواعيد</button></div></article>`).join('')}
function renderParks(){const box=$('parkCards');if(!box)return;box.innerHTML=[['حديقة الأمير فهد','أنشطة يومية ومساحات عائلية'],['الحديقة المركزية','فعاليات وورش متنوعة'],['حديقة متنفس','تجربة آمنة وممتعة للأطفال']].map((p,i)=>`<article class="card"><div class="pic"></div><div class="pad"><h3>${p[0]}</h3><p>${p[1]}</p><button class="ghost">استعراض الأنشطة</button></div></article>`).join('')}
renderActivities();renderParks();
let extra=[];
window.addRegisterChild=()=>{extra.push(extra.length);const d=document.createElement('div');d.className='extra-child';d.innerHTML=`<input class="xChildName" placeholder="اسم الطفل"><div class="formGrid"><input class="xChildDob" type="date"><select class="xChildGender"><option>ذكر</option><option>أنثى</option></select></div><textarea class="xChildNotes" placeholder="ملاحظات (اختياري)"></textarea>`;$('extraChildren').appendChild(d)};
$('registerParentBtn')?.addEventListener('click',async()=>{try{const email=$('regEmail').value.trim(),pass=$('regPassword').value,name=$('regParent').value.trim();if(!email||pass.length<6||!name||!$('regChild').value.trim())return toast('أكمل البيانات المطلوبة');const cr=await createUserWithEmailAndPassword(auth,email,pass);await updateProfile(cr.user,{displayName:name});await setDoc(doc(db,'users',cr.user.uid),{name,phone:$('regPhone').value.trim(),email,role:'parent',createdAt:serverTimestamp()});const children=[{name:$('regChild').value.trim(),dob:$('regChildDob').value,gender:$('regChildGender').value,notes:$('regChildNotes').value.trim()}];document.querySelectorAll('.extra-child').forEach(x=>children.push({name:x.querySelector('.xChildName').value.trim(),dob:x.querySelector('.xChildDob').value,gender:x.querySelector('.xChildGender').value,notes:x.querySelector('.xChildNotes').value.trim()}));for(const ch of children.filter(x=>x.name))await addDoc(collection(db,'children'),{...ch,parentId:cr.user.uid,createdAt:serverTimestamp()});closeModal('registerModal');toast('تم إنشاء الحساب بنجاح');await loadParent(cr.user)}catch(e){toast(e.code==='auth/email-already-in-use'?'البريد مسجل مسبقًا':'تعذر إنشاء الحساب')}});
$('parentLoginBtn')?.addEventListener('click',async()=>{try{const cr=await signInWithEmailAndPassword(auth,$('loginEmail').value.trim(),$('loginPassword').value);closeModal('loginModal');toast('مرحبًا بك');await loadParent(cr.user)}catch(e){toast('البريد أو كلمة المرور غير صحيحة')}});
$('addChildBtn')?.addEventListener('click',async()=>{if(!auth.currentUser)return openModal('loginModal');const name=$('newChildName').value.trim();if(!name)return toast('اكتب اسم الطفل');await addDoc(collection(db,'children'),{parentId:auth.currentUser.uid,name,age:Number($('newChildAge').value||0),gender:$('newChildGender').value,notes:$('newChildNotes').value.trim(),createdAt:serverTimestamp()});closeModal('childModal');toast('تمت إضافة الطفل');loadParent(auth.currentUser)});
async function loadParent(u){if(!u)return;$('parentName').textContent=u.displayName||'ولي الأمر';const q=query(collection(db,'children'),where('parentId','==',u.uid)),s=await getDocs(q);$('childCount').textContent=s.size;$('childrenList').innerHTML=s.empty?'<p>لا يوجد أطفال مضافون.</p>':s.docs.map(d=>{const x=d.data();return `<p><b>${esc(x.name)}</b><span>${x.age?esc(x.age)+' سنوات':esc(x.gender||'')}</span></p>`}).join('')}
$('feedbackForm')?.addEventListener('submit',async e=>{e.preventDefault();const rating=document.querySelector('input[name="r"]:checked')?.id?.replace('r','')||null;await addDoc(collection(db,'feedback'),{userId:auth.currentUser?.uid||null,type:$('feedbackType').value,rating:Number(rating)||null,text:$('feedbackText').value.trim(),createdAt:serverTimestamp()});$('feedbackText').value='';toast('شكرًا، وصلنا رأيك')});
$('bookingBtn')?.addEventListener('click',async()=>{if(!auth.currentUser){openModal('loginModal');return toast('سجّل الدخول أولًا')};const cs=await getDocs(query(collection(db,'children'),where('parentId','==',auth.currentUser.uid)));if(cs.empty)return toast('أضف بيانات الطفل أولًا');const child=cs.docs[0];await addDoc(collection(db,'bookings'),{parentId:auth.currentUser.uid,childId:child.id,childName:child.data().name,activity:'الرسم والتلوين',date:$('bookingDate').value||'',status:'مؤكد',createdAt:serverTimestamp()});toast('تم تأكيد الحجز')});
onAuthStateChanged(auth,u=>{if(u)loadParent(u).catch(()=>{})});