let auth,db;firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();
const cats=['القراءة والقصص','الرسم والفنون','الزراعة والبيئة','الألعاب الجماعية'];
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');scrollTo(0,0);if(id==='parent')loadParent();if(id==='admin')loadAdmin()}
function msg(id,t,ok=true){let e=document.getElementById(id);e.textContent=t;e.style.color=ok?'#28704f':'#a83232'}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function iso(d){return d.toISOString().slice(0,10)} function addDays(n){let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return iso(d)}
const defaults=[
['حكاية تصنع خيالًا','القراءة والقصص',1,'17:00',15],['مغامرة بين الصفحات','القراءة والقصص',5,'18:00',15],['نادي القارئ الصغير','القراءة والقصص',10,'17:30',15],
['ألواني الجميلة','الرسم والفنون',2,'17:00',12],['ارسم عالمك','الرسم والفنون',6,'18:30',12],['الفنان الصغير','الرسم والفنون',11,'17:00',12],
['ازرع نبتتك','الزراعة والبيئة',3,'16:30',14],['أصدقاء البيئة','الزراعة والبيئة',7,'17:30',14],['حديقتي الصغيرة','الزراعة والبيئة',12,'16:30',14],
['فريق المرح','الألعاب الجماعية',4,'17:00',18],['نتعاون ونلعب','الألعاب الجماعية',8,'18:00',18],['تحدي الأصدقاء','الألعاب الجماعية',13,'17:30',18]];
async function seed(){const s=await db.collection('workshops').limit(1).get();if(!s.empty)return;for(const x of defaults)await db.collection('workshops').add({title:x[0],category:x[1],date:addDays(x[2]),time:x[3],capacity:x[4],booked:0,location:'حديقة الراجحي - تبوك',createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
regForm.onsubmit=async e=>{e.preventDefault();try{let c=await auth.createUserWithEmailAndPassword(email.value,password.value),u=c.user;await db.collection('users').doc(u.uid).set({name:parentName.value,phone:phone.value,email:email.value});let ch=await db.collection('children').add({parentId:u.uid,name:childName.value,age:+age.value,notes:notes.value});localStorage.setItem('motChild',JSON.stringify({id:ch.id,name:childName.value,age:+age.value}));await seed();show('parent')}catch(x){msg('formMsg',x.code==='auth/email-already-in-use'?'البريد مسجل مسبقًا، استخدم تسجيل الدخول.':'تعذر التسجيل: '+x.message,false)}};
loginForm.onsubmit=async e=>{e.preventDefault();try{await auth.signInWithEmailAndPassword(loginEmail.value,loginPassword.value);await seed();show('parent')}catch(x){msg('loginMsg','البريد أو كلمة المرور غير صحيحة.',false)}};
logoutBtn.onclick=async()=>{await auth.signOut();show('home')};activityDate.onchange=()=>loadSchedule(activityDate.value);function resetDate(){activityDate.value='';loadSchedule()}
async function getChild(){let c=JSON.parse(localStorage.getItem('motChild')||'null');if(c)return c;let s=await db.collection('children').where('parentId','==',auth.currentUser.uid).limit(1).get();if(!s.empty){let d=s.docs[0];c={id:d.id,...d.data()};localStorage.setItem('motChild',JSON.stringify(c));return c}return null}
async function loadParent(){if(!auth.currentUser){show('login');return}await seed();loadSchedule();loadBookings()}
async function loadSchedule(day=''){let s=await db.collection('workshops').get(),a=[];s.forEach(d=>a.push({id:d.id,...d.data()}));let end=addDays(14),today=addDays(0);a=a.filter(x=>x.date>=today&&x.date<=end&&(!day||x.date===day)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));schedule.innerHTML=a.length?a.map(x=>{let left=Math.max(0,x.capacity-(x.booked||0));return '<article><span class="seats '+(!left?'full':'')+'">'+(left?'متبقي '+left+' من '+x.capacity:'مكتمل')+'</span><h3>'+esc(x.title)+'</h3><p class="meta">'+esc(x.category)+'<br>📅 '+x.date+' · ⏰ '+x.time+'<br>📍 '+esc(x.location)+'</p><button '+(!left?'disabled':'')+' onclick="book(\''+x.id+'\')">حجز المقعد</button></article>'}).join(''):'<p>لا توجد ورش في هذا التاريخ.</p>'}
async function book(id){let child=await getChild();if(!child)return alert('أضيفي بيانات الطفل أولًا.');let ref=db.collection('workshops').doc(id);try{await db.runTransaction(async t=>{let s=await t.get(ref),w=s.data(),left=w.capacity-(w.booked||0);if(left<=0)throw Error('FULL');let old=await db.collection('bookings').where('parentId','==',auth.currentUser.uid).where('workshopId','==',id).get();if(!old.empty)throw Error('DUP');t.update(ref,{booked:firebase.firestore.FieldValue.increment(1)});let b=db.collection('bookings').doc();t.set(b,{parentId:auth.currentUser.uid,childId:child.id,childName:child.name,age:child.age,workshopId:id,workshopTitle:w.title,activity:w.category,date:w.date,time:w.time,status:'مؤكد',createdAt:firebase.firestore.FieldValue.serverTimestamp()})});alert('تم حجز المقعد بنجاح ✓');loadParent()}catch(e){alert(e.message==='FULL'?'اكتملت المقاعد.':e.message==='DUP'?'تم حجز هذه الورشة مسبقًا.':'تعذر الحجز.')}}
async function loadBookings(){let s=await db.collection('bookings').where('parentId','==',auth.currentUser.uid).get(),a=[];s.forEach(d=>a.push(d.data()));bookings.innerHTML=a.length?a.map(x=>'<div class="booking"><b>'+esc(x.childName)+' — '+esc(x.workshopTitle||x.activity)+'</b><br>📅 '+esc(x.date)+' '+esc(x.time||'')+' · '+esc(x.status||'مؤكد')+'</div>').join(''):'<p>لا توجد حجوزات حتى الآن.</p>'}
suggestionForm.onsubmit=async e=>{e.preventDefault();await db.collection('suggestions').add({parentId:auth.currentUser?.uid||null,type:suggestType.value,text:suggestText.value,createdAt:firebase.firestore.FieldValue.serverTimestamp()});suggestText.value='';msg('suggestMsg','شكرًا، تم إرسال اقتراحك ✓')};
workshopForm.onsubmit=async e=>{e.preventDefault();await db.collection('workshops').add({title:wTitle.value,category:wCategory.value,date:wDate.value,time:wTime.value,capacity:+wCapacity.value,booked:0,location:'حديقة الراجحي - تبوك',createdAt:firebase.firestore.FieldValue.serverTimestamp()});e.target.reset();wCapacity.value=15;msg('workshopMsg','تمت إضافة الورشة ✓');loadAdmin()};
async function loadAdmin(){await seed();let ws=await db.collection('workshops').get(),bs=await db.collection('bookings').get(),ss=await db.collection('suggestions').get(),w=[],b=[];ws.forEach(d=>w.push({id:d.id,...d.data()}));bs.forEach(d=>b.push(d.data()));statBookings.textContent=b.length;statChildren.textContent=new Set(b.map(x=>x.childId)).size;statWorkshops.textContent=w.filter(x=>x.date>=addDays(0)).length;statSeats.textContent=w.reduce((n,x)=>n+Math.max(0,x.capacity-(x.booked||0)),0);let counts={};cats.forEach(c=>counts[c]=0);b.forEach(x=>counts[x.activity]=(counts[x.activity]||0)+1);let max=Math.max(1,...Object.values(counts));activityBars.innerHTML=Object.entries(counts).map(([k,v])=>'<div class="barrow"><span>'+k+'</span><div class="bar"><i style="width:'+(v/max*100)+'%"></i></div><b>'+v+'</b></div>').join('');workshopTable.innerHTML='<table class="table"><tr><th>الورشة</th><th>التاريخ</th><th>المسجلون</th><th>المتبقي</th></tr>'+w.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+x.date+' '+x.time+'</td><td>'+(x.booked||0)+'</td><td>'+Math.max(0,x.capacity-(x.booked||0))+'</td></tr>').join('')+'</table>';let su=[];ss.forEach(d=>su.push(d.data()));suggestionsList.innerHTML=su.length?su.map(x=>'<div class="suggestion"><b>'+esc(x.type)+'</b><p>'+esc(x.text)+'</p></div>').join(''):'<p>لا توجد اقتراحات بعد.</p>'}
auth.onAuthStateChanged(u=>{});