firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();const ADMIN_EMAIL="ragged603@gmail.com";let user=null,children=[];
const $=x=>document.getElementById(x),esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));function show(x){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(x).classList.add("active")}function dateAr(x){return new Date(x+"T12:00:00").toLocaleDateString("ar-SA",{weekday:"long",day:"numeric",month:"long"})}function clearDate(){$("activityDate").value="";loadWorkshops()}
auth.onAuthStateChanged(async u=>{user=u;if(!u)return;let d=await db.collection("users").doc(u.uid).get(),profile=d.exists?d.data():{};if(u.email&&u.email.toLowerCase()===ADMIN_EMAIL){await db.collection("users").doc(u.uid).set({email:u.email,role:"admin",name:profile.name||"إدارة متنفس"},{merge:true});show("admin");loadAdmin()}else{if(!d.exists)await db.collection("users").doc(u.uid).set({email:u.email,role:"parent"},{merge:true});show("parent");loadParent()}});
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMsg").textContent="";try{await auth.signInWithEmailAndPassword($("loginEmail").value.trim(),$("loginPassword").value)}catch(e){$("loginMsg").textContent="تعذر تسجيل الدخول. تأكد من البريد وكلمة المرور."}};
$("registerForm").onsubmit=async e=>{e.preventDefault();try{let c=await auth.createUserWithEmailAndPassword($("regEmail").value.trim(),$("regPassword").value);await db.collection("users").doc(c.user.uid).set({name:$("parentName").value,phone:$("parentPhone").value,email:c.user.email,role:"parent",createdAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){$("registerMsg").textContent="تعذر إنشاء الحساب: "+e.message}};
async function logout(){await auth.signOut();children=[];show("home")}function parentTab(n){document.querySelectorAll("#parent .tab").forEach(x=>x.classList.add("hidden"));$("p-"+n).classList.remove("hidden");if(n==="children")loadChildren();if(n==="bookings")loadBookings()}async function loadParent(){await loadChildren();await loadWorkshops()}$("activityDate").onchange=loadWorkshops;
async function loadChildren(){if(!user)return;let q=await db.collection("children").where("parentUid","==",user.uid).get();children=q.docs.map(d=>({id:d.id,...d.data()}));$("childrenList").innerHTML=children.length?children.map(c=>'<div class="workshop"><b>'+esc(c.name)+'</b> — '+c.age+' سنوات'+(c.notes?'<p>'+esc(c.notes)+'</p>':'')+'</div>').join(""):'<p class="muted">لم تتم إضافة أطفال بعد.</p>'}
$("childForm").onsubmit=async e=>{e.preventDefault();await db.collection("children").add({parentUid:user.uid,name:$("childName").value,age:Number($("childAge").value),notes:$("childNotes").value,createdAt:firebase.firestore.FieldValue.serverTimestamp()});e.target.reset();loadChildren()};
async function loadWorkshops(){let q=await db.collection("workshops").get(),sel=$("activityDate").value,a=q.docs.map(d=>({id:d.id,...d.data()})).filter(w=>!sel||w.date===sel).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$("schedule").innerHTML=a.length?a.map(w=>{let left=Math.max(0,(w.capacity||0)-(w.booked||0)),closed=w.status!=="available"||left===0,label=w.status==="cancelled"?"ملغاة":left===0||w.status==="full"?"مكتملة":"متبقي "+left+" مقاعد";return '<article class="workshop"><span class="tag">'+esc(w.category)+'</span><h3>'+esc(w.title)+'</h3><p>'+dateAr(w.date)+' • '+esc(w.time)+'</p><p>'+esc(w.location||"حديقة متنفس")+' • العمر '+esc(w.ageRange||"5-10")+'</p><b>'+label+'</b><br><br><button class="gold" '+(closed?"disabled":"")+' onclick="book(\''+w.id+'\')">احجز الآن</button></article>'}).join(""):'<p class="muted">لا توجد ورش في هذا التاريخ.</p>'}
async function book(id){await loadChildren();if(!children.length){alert("أضيفي طفلًا أولًا.");parentTab("children");return}let child=children[0];if(children.length>1){let n=Number(prompt("اختاري رقم الطفل:\n"+children.map((c,i)=>(i+1)+"- "+c.name).join("\n")))-1;if(n<0||!children[n])return;child=children[n]}let dup=await db.collection("bookings").where("parentUid","==",user.uid).where("workshopId","==",id).get();if(dup.docs.some(d=>d.data().childId===child.id)){alert("هذا الطفل مسجل مسبقًا.");return}let ref=db.collection("workshops").doc(id);try{await db.runTransaction(async t=>{let s=await t.get(ref),w=s.data();if(!w||w.status!=="available"||(w.booked||0)>=(w.capacity||0))throw Error("full");let b=db.collection("bookings").doc();t.set(b,{parentUid:user.uid,childId:child.id,childName:child.name,workshopId:id,workshopTitle:w.title,category:w.category,date:w.date,time:w.time,status:"confirmed",createdAt:firebase.firestore.FieldValue.serverTimestamp()});t.update(ref,{booked:firebase.firestore.FieldValue.increment(1)})});alert("تم الحجز بنجاح");loadWorkshops()}catch(e){alert("تعذر الحجز أو اكتملت المقاعد.")}}
async function loadBookings(){let q=await db.collection("bookings").where("parentUid","==",user.uid).get(),a=q.docs.map(d=>d.data()).sort((a,b)=>(a.date||"").localeCompare(b.date||""));$("bookingsList").innerHTML=a.length?a.map(b=>'<div class="workshop"><b>'+esc(b.workshopTitle)+'</b><p>'+esc(b.childName)+' • '+dateAr(b.date)+' • '+esc(b.time)+'</p><span>✓ مؤكد</span></div>').join(""):'<p class="muted">لا توجد حجوزات بعد.</p>'}
$("suggestionForm").onsubmit=async e=>{e.preventDefault();await db.collection("suggestions").add({parentUid:user.uid,type:$("suggestionType").value,text:$("suggestionText").value,createdAt:firebase.firestore.FieldValue.serverTimestamp()});e.target.reset();alert("شكرًا، وصل اقتراحك.")};
function adminTab(n){document.querySelectorAll("#admin .tab").forEach(x=>x.classList.add("hidden"));$("a-"+n).classList.remove("hidden");if(n==="workshops")loadAdminWorkshops();if(n==="registrations")loadRegistrations();if(n==="children")loadAdminChildren();if(n==="suggestions")loadAdminSuggestions()}
$("workshopForm").onsubmit=async e=>{e.preventDefault();await db.collection("workshops").add({title:$("wTitle").value,category:$("wCategory").value,date:$("wDate").value,time:$("wTime").value,ageRange:$("wAge").value,capacity:Number($("wCapacity").value),booked:0,location:$("wLocation").value,description:$("wDescription").value,status:$("wStatus").value,createdAt:firebase.firestore.FieldValue.serverTimestamp()});e.target.reset();$("wAge").value="5-10";$("wLocation").value="حديقة متنفس";loadAdminWorkshops();loadAdmin()};
async function loadAdmin(){let [w,b,c,s]=await Promise.all(["workshops","bookings","children","suggestions"].map(x=>db.collection(x).get())),ws=w.docs.map(d=>d.data()),bs=b.docs.map(d=>d.data()),cap=ws.reduce((n,x)=>n+(x.capacity||0),0),used=ws.reduce((n,x)=>n+(x.booked||0),0);$("stats").innerHTML=[["الأطفال",c.size],["الحجوزات",b.size],["الورش",w.size],["المقاعد المتبقية",Math.max(0,cap-used)],["الاقتراحات",s.size]].map(x=>'<div class="stat"><strong>'+x[1]+'</strong>'+x[0]+'</div>').join("");let cats=["القراءة والقصص","الرسم والفنون","الزراعة والبيئة","الألعاب الجماعية"],counts=Object.fromEntries(cats.map(x=>[x,0]));bs.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);let max=Math.max(1,...Object.values(counts));$("activityBars").innerHTML=cats.map(x=>'<b>'+x+' ('+counts[x]+')</b><div class="bar"><span style="width:'+Math.max(5,counts[x]/max*100)+'%">'+counts[x]+'</span></div>').join("")}
function table(h,rows){return '<div class="table"><table><thead><tr>'+h.map(x=>"<th>"+x+"</th>").join("")+'</tr></thead><tbody>'+rows.map(r=>"<tr>"+r.map(x=>"<td>"+x+"</td>").join("")+"</tr>").join("")+"</tbody></table></div>"}
async function loadAdminWorkshops(){let q=await db.collection("workshops").get(),a=q.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.date||"").localeCompare(b.date||""));$("adminWorkshops").innerHTML=table(["الورشة","النشاط","التاريخ","السعة","المسجلون","الحالة",""],a.map(w=>[esc(w.title),esc(w.category),esc(w.date)+" "+esc(w.time),w.capacity||0,w.booked||0,esc(w.status),'<button class="danger" onclick="deleteWorkshop(\''+w.id+'\')">حذف</button>']))}
async function deleteWorkshop(id){if(confirm("حذف هذه الورشة؟")){await db.collection("workshops").doc(id).delete();loadAdminWorkshops();loadAdmin()}}async function loadRegistrations(){let q=await db.collection("bookings").get(),a=q.docs.map(d=>d.data());$("registrationsTable").innerHTML=table(["الطفل","الورشة","النشاط","التاريخ","الحالة"],a.map(x=>[esc(x.childName),esc(x.workshopTitle),esc(x.category),esc(x.date)+" "+esc(x.time),esc(x.status)]))}async function loadAdminChildren(){let q=await db.collection("children").get(),a=q.docs.map(d=>d.data());$("adminChildren").innerHTML=table(["اسم الطفل","العمر","الملاحظات"],a.map(x=>[esc(x.name),x.age,esc(x.notes||"—")]))}async function loadAdminSuggestions(){let q=await db.collection("suggestions").get(),a=q.docs.map(d=>d.data());$("adminSuggestions").innerHTML=a.length?a.map(x=>'<div class="workshop"><span class="tag">'+esc(x.type)+'</span><p>'+esc(x.text)+'</p></div>').join(""):'<p class="muted">لا توجد اقتراحات.</p>'}